### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by seabbs** [HopkinsIDD/cholera_seasonality_ssa#1]
Hi, 

I enjoyed the paper. Great job producing a useful and detailed SI -  lovely to see. I wondered when the code might be available as I would be interested in reproducing the results and exploring the implementation. Lack of code is also obviously a blocker to making use of the results!

Sam

**Comment by scottyaz** [comment]
Hi Sam - Really sorry about the delay but we are working on getting it cleaned up and shared. Will ping you when its up. 

Thanks,
Andrew

**Comment by javierps** [comment]
Hello Sam,

Thanks a lot for your interest!

Things took a little more time than expected but we have just pushed the code for the analysis in the `main` branch, and you can find all data to replicate results, and outputs to replicate the figures in the `for_replication` branch.

We will be updating the description of the details of project implementation soon (`notebooks/project_details.Rmd`), but don't hesitate to write if you have any questions/feedabck by then.

Best,
Javier

**Comment by seabbs** [comment]
Thanks for flagging

Already having fun 😆 

https://github.com/HopkinsIDD/cholera_seasonality_ssa/blob/25b1701ed6f933d7cbf35aa2a7b6e30c857c98ed/analysis/stan/binomial_bym2_fast_convolved_lambda_flexmixture_speedup_map_rect_v2_generate.stan#L16

Joking aside great to see effort that has gone into the code base. Looking forward to reading in detail (in future I would really stress how useful it is to have everything ready at once (i.e code and preprint) - it can be really hard to make time to go through work twice).

Sam

**Comment by javierps** [comment]
Hi Sam,

I understand and will try to make it for next time, and happy to see that efforts are appreciated!

Javier
